_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  #WEIGHTS: "./output/model_0139999.pth" #"detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  #WEIGHTS: "./datasets/pretrained_models/model_R50_C4.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: './output/fsod/R_50_C4_1x'
